version: "3.8"

services:
  frontend:
    build:
      context: ./Client
      dockerfile: ../Containers/Frontend/Dockerfile.${NODE_ENV}
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - CHOKIDAR_USEPOLLING=true  # Add this to enable polling for file changes
    volumes:
      - ./Client:/app  # Mount local files into the container
      - /app/node_modules  # Prevents conflicts with host node_modules