import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Netflix-Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        
        {children}
        
        <footer>
          
            <a href="">Questions? Contact us.</a>
            <a href="">FAQ</a>
            <a href="">Account.</a>
            <a href="">Investor Relations</a>
            <a href="">Ways to Watch</a>
            <a href="">Privacy</a>
            <a href="">Corporate Information</a>
            <a href="">Speed Test</a>
            <a href="">Only on Netflix</a>
            <a href="">Help Center</a>
            <a href="">Media Center</a>
            <a href="">Jobs</a>
            <a href="">Cookie Preferences</a>
            <a href="">Legal Notices</a>
       
        </footer>
        </body>
        
    </html>
  );
}
